Feature/homework 4 lists
ilhan76/MTS.Teta_project pull request #4
Opened 2021-07-20 14:11 UTC by ilhan76

2021-07-20 21:09 UTC, maxlord requested changes

2021-07-20 21:09 UTC, maxlord commented on app/src/main/java/com/kudashov/mtsteta_project/adapters/GenresAdapter.kt
> +    class GenreViewHolder(var view: View, var delegate: GenresDelegate): RecyclerView.ViewHolder(view){
Параметры, передаваемые в конструктор нужно делать val-ами. Только если нужно в процессе менять эти переменные, только тогда нужно делать var, но эти бывает редко, и явлется анти-паттерном), лучше так не делать.

2021-07-20 21:09 UTC, maxlord commented on app/src/main/java/com/kudashov/mtsteta_project/adapters/GenresAdapter.kt
> +            view.setOnClickListener {
Листенеры устанавливать лучше в конструкторе или блоке init.

2021-07-20 21:09 UTC, maxlord commented on app/src/main/java/com/kudashov/mtsteta_project/adapters/GenresAdapter.kt
> +            view.setOnClickListener {
В обработчике клика надо понимать что за элемент кликнут, для этого обычно или в тег вьюшки кладут объект или хранят его в каком-то локальном поле, и в бинде сетят его.

2021-07-20 21:09 UTC, maxlord commented on app/src/main/java/com/kudashov/mtsteta_project/adapters/MoviesAdapter.kt
> +        var card: CardView = view.findViewById(R.id.cardPoster)
`private val`-ами можно сделать

2021-07-20 21:09 UTC, maxlord commented on app/src/main/java/com/kudashov/mtsteta_project/adapters/MoviesAdapter.kt
> +        fun bind(movie: MovieDto){
Форматирование

2021-07-20 21:09 UTC, maxlord commented on app/src/main/java/com/kudashov/mtsteta_project/adapters/MoviesAdapter.kt
> +            ageLimit.text = "${movie.ageRestriction}+"
Хард-код, лучше вынести в строковый ресурс с шаблоном "%d+"

2021-07-20 21:09 UTC, maxlord commented on app/src/main/java/com/kudashov/mtsteta_project/customView/MyRatingBar.kt
> +        val filled = ContextCompat.getDrawable(context, R.drawable.ic_star_filled)
В onDraw не рекомендуется создавать объекты. Вынеси их в поля класса и инициализируй в конструкторе.
onDraw будет вызываться 60 раз в секунду.

2021-07-20 21:09 UTC, maxlord commented on app/src/main/java/com/kudashov/mtsteta_project/data/source/impl/GenreDataSourceImpl.kt
> +    override fun getGenre(): List<Genre> {
может getGenres(), все таки список возвращается

2021-07-20 21:09 UTC, maxlord commented on app/src/main/java/com/kudashov/mtsteta_project/screens/MovieList.kt
> +    private val mBinding get() = _binding!!
Избегаем венгерской нотации. Именования с префиксом m.

2021-07-20 21:09 UTC, maxlord commented on app/src/main/res/layout/fragment_movie_details.xml
> +
Форматирование:
1. Между виджетами должны быть 1 пустая строка
2. Пустых строк не должно быть в обявлении виджета, встречаются такие, где до закрывающегося тега есть пустые строки

2021-07-20 21:09 UTC, maxlord commented on app/src/main/res/layout/fragment_movie_list.xml
> +        android:id="@+id/search"
ibSearch

2021-07-21 03:05 UTC, ilhan76 commented on app/src/main/java/com/kudashov/mtsteta_project/adapters/MoviesAdapter.kt
> +        var card: CardView = view.findViewById(R.id.cardPoster)
Что именно? CardView и тд или что в конструкторе?

2021-07-21 16:40 UTC, maxlord requested changes

2021-07-21 16:40 UTC, maxlord commented on app/src/main/java/com/kudashov/mtsteta_project/adapters/viewHolders/ActorViewHolder.kt
> +    fun onBind(actor: Actor) {
Этот метода где-то назвается `bind`, где-то `onBind`. Надо привести к единообразию. Приставку on добавляют обычно в колбек-функции, которые можно переопределить или вызывать при каком-то событии. 
В данном контексте лучше юзать без приставки.

2021-07-25 06:33 UTC, merged